---
title: "Hollywood Movies Profit"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    highlight: default
    code_folding: hide
    self_contained: False
---


```{r setup, include=FALSE}
library(knitr)
options(max.print="75")
opts_chunk$set(
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```


# Data

```{r}
library(here)

source(here("scripts/read_data.R"))

data<- read_and_save_data(here("data/raw/movie_profit.csv"),here("data/clean/movie_profit.RDS"))
```


# Plots

## Age ratings and genres

```{r}
source(here("scripts/plots_small.R"))
```


```{r}
plot_1(data)
```


```{r}
plot_6(data)
```




```{r}
plot_3(data)
```

## Budgets and profit


```{r}
plot_2(data)
```


```{r}
plot_4(data)
```

```{r}
plot_5(data)
```


```{r}
library(priceR)
data2 <- data %>%
  mutate(
    production_budget = adjust_for_inflation(production_budget, year, "US", to_date = 2019),
    worldwide_gross = adjust_for_inflation(worldwide_gross, year, "US", to_date = 2019)
  ) %>%
  filter(year %in% 1980:1989)

saveRDS(data2,here("data/clean/movie_profit_adjusted_for_inflation.RDS"))

source(here("scripts/plots_panel.R"))
```
# 80s deep dive

## One-by-one {.tabset}

### 1.

```{r}
p1 <- panel_1(data2)
p1
```

### 2.

```{r}
p2 <- panel_2(data2)
p2
```

### 3.

```{r}
p3 <- panel_3(data2)
p3
```

### 4.

```{r}
p4 <- panel_4(data2)
p4
```

## Putting it into an infographic

```{r fig.width=17,fig.height=12}
library(patchwork)
a <- "AAAAACC
AAAAACC
AAAAACC
AAAAACC
BBBBBDD
BBBBBDD
BBBBBDD"
p3 + p4 + p1 + p2 + plot_layout(design = a) +
  plot_annotation(title = "80s movies", theme = theme(plot.title = element_text(size = 32, family = "Roboto Condensed")))
```



# Code

```{r, code=readLines(here("scripts/plots_small.R")), eval=FALSE}

```

```{r, code=readLines(here("scripts/plots_panel.R")), eval=FALSE}

```


# Session info

```{r}
devtools::session_info()
```

